"""Turn resolved prototypes into the contract models (``models.py``).

Defaults follow the game's C# prototype classes, e.g. ``ReactionPrototype`` (minTemp 0, maxTemp
infinity) and ``FoodRecipePrototype`` (time 5, group "Other", deviceType Microwave).
"""

import math
import re
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import PurePosixPath
from typing import Any, TypeVar

from pydantic import BaseModel, ValidationError

from ss14help_pipeline.localize import Localizer
from ss14help_pipeline.models import (
    CookingRecipe,
    Entity,
    Mixer,
    Reactant,
    Reaction,
    Reagent,
    Source,
)
from ss14help_pipeline.prototypes import Prototype, PrototypeIndex
from ss14help_pipeline.warnings import WarningLog

M = TypeVar("M", bound=BaseModel)

GENERIC_CATEGORIES = {"reactions", "reaction", "recipes", "misc", "other"}
"""File stems that say nothing about the recipe; fall back to the product's reagent group."""

HEX_COLOR = re.compile(r"^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$")


@dataclass
class UpstreamIds:
    """Ids present in the upstream snapshot; anything else is ``serverOnly``."""

    reagents: set[str] = field(default_factory=set)
    entities: set[str] = field(default_factory=set)
    reactions: set[str] = field(default_factory=set)
    cooking: set[str] = field(default_factory=set)


@dataclass
class Normalized:
    reagents: list[Reagent]
    entities: list[Entity]
    reactions: list[Reaction]
    cooking: list[CookingRecipe]
    mixers: list[Mixer]
    sources: list[Source]


class Normalizer:
    def __init__(
        self,
        index: PrototypeIndex,
        loc: Localizer,
        log: WarningLog,
        upstream: UpstreamIds | None = None,
    ) -> None:
        self.index = index
        self.loc = loc
        self.log = log
        self.upstream = upstream

    def run(self) -> Normalized:
        dispensable = self.dispensable_reagents()
        reagents = self._all(self.index.concrete("reagent"), lambda p: self.reagent(p, dispensable))
        groups = {r.id: r.group for r in reagents}
        reactions = self._all(self.index.concrete("reaction"), lambda p: self.reaction(p, groups))
        cooking = self._all(self.index.concrete("microwaveMealRecipe"), self.cooking)
        mixers = self._all(self.index.concrete("mixingCategory"), self.mixer)
        sources = self._all(self.index.concrete("entity"), self.source)

        referenced = {c.result for c in cooking} | {s.entity for s in sources}
        for c in cooking:
            referenced.update(c.solids)
        entities = [e for e in (self.entity(i) for i in sorted(referenced)) if e is not None]

        return Normalized(
            reagents=reagents,
            entities=entities,
            reactions=reactions,
            cooking=cooking,
            mixers=mixers,
            sources=sources,
        )

    def _all(self, protos: Iterable[Prototype], convert: Any) -> list[Any]:
        """Convert each prototype; one bad prototype is a warning, not a failed build."""
        out = []
        for proto in protos:
            try:
                item = convert(proto)
            except (ValidationError, ValueError, TypeError) as e:
                first = str(e).splitlines()[0] if str(e) else type(e).__name__
                self.log.add(
                    "invalid-prototype", f"{proto.type} {proto.id}: {first}", proto.source_file
                )
                continue
            if item is not None:
                out.append(item)
        return out

    def _server_only(self, kind: str, proto_id: str) -> bool:
        if self.upstream is None:
            return False
        return proto_id not in getattr(self.upstream, kind)

    # --- reagents ------------------------------------------------------------------------

    def reagent(self, p: Prototype, dispensable: set[str]) -> Reagent:
        d = p.data
        color = d.get("color")
        return Reagent(
            id=p.id,
            name=self.loc.text(d.get("name"), p.id) or p.id,
            desc=self.loc.text(d.get("desc")),
            physical_desc=self.loc.text(d.get("physicalDesc")),
            group=_str_or_none(d.get("group")),
            color=color if isinstance(color, str) and HEX_COLOR.match(color) else None,
            dispensable=p.id in dispensable,
            source_file=p.source_file,
            server_only=self._server_only("reagents", p.id),
        )

    def dispensable_reagents(self) -> set[str]:
        """Reagents stocked in (or generated by) any reagent dispenser that spawns filled."""
        out: set[str] = set()
        for ent in self.index.concrete("entity"):
            dispenser = ent.component("ReagentDispenser")
            if dispenser is None:
                continue
            # Starlight: reagents the dispenser makes from power.
            out.update(str(k) for k in (dispenser.get("generatableReagents") or {}))
            # Older layout: a reagentDispenserInventory prototype listing reagent ids.
            pack = dispenser.get("pack")
            if isinstance(pack, str) and (inv := self.index.get("reagentDispenserInventory", pack)):
                out.update(str(r) for r in inv.data.get("inventory") or [])
            # Current layout: the dispenser spawns filled with jugs/bottles.
            fill = ent.component("EntityTableContainerFill") or ent.component("ContainerFill")
            for jug_id in _entity_ids(fill.get("containers") if fill else None):
                jug = self.index.get("entity", jug_id)
                if jug is not None:
                    out.update(_solution_reagents(jug, None))
        return out

    # --- recipes -------------------------------------------------------------------------

    def reaction(self, p: Prototype, groups: dict[str, str | None]) -> Reaction:
        d = p.data
        reactants = {
            str(rid): Reactant(
                amount=_amount((spec or {}).get("amount", 1)),
                catalyst=bool((spec or {}).get("catalyst", False)),
            )
            for rid, spec in (d.get("reactants") or {}).items()
        }
        products = {str(k): _amount(v) for k, v in (d.get("products") or {}).items()}
        min_temp = _float_or_none(d.get("minTemp"))
        max_temp = _float_or_none(d.get("maxTemp"))
        return Reaction(
            id=p.id,
            category=self._category(p, products, groups),
            reactants=reactants,
            products=products,
            min_temp=min_temp if min_temp else None,
            max_temp=max_temp if max_temp is not None and math.isfinite(max_temp) else None,
            mixers=[str(m) for m in d.get("requiredMixerCategories") or []],
            quantized=bool(d.get("quantized", False)),
            priority=int(d.get("priority", 0)),
            effects=[_jsonable(e) for e in d.get("effects") or [] if isinstance(e, dict)],
            source_file=p.source_file,
            server_only=self._server_only("reactions", p.id),
        )

    def _category(
        self, p: Prototype, products: dict[str, float], groups: dict[str, str | None]
    ) -> str:
        stem = PurePosixPath(p.source_file).stem.lower()
        if stem not in GENERIC_CATEGORIES:
            return stem
        primary = (
            p.id if p.id in products else max(products, key=lambda k: products[k], default=None)
        )
        group = groups.get(primary) if primary else None
        return group.lower() if group else "misc"

    def cooking(self, p: Prototype) -> CookingRecipe:
        d = p.data
        result = str(d["result"])
        name = self.loc.text(d.get("name")) or self._entity_name(result)
        return CookingRecipe(
            id=p.id,
            name=name,
            device=str(d.get("deviceType", "Microwave")),
            time=float(d.get("time", 5)),
            solids={str(k): _count(v) for k, v in (d.get("solids") or {}).items()},
            reagents={str(k): _amount(v) for k, v in (d.get("reagents") or {}).items()},
            result=result,
            group=str(d.get("group", "Other")),
            secret=bool(d.get("secretRecipe", False)),
            source_file=p.source_file,
            server_only=self._server_only("cooking", p.id),
        )

    def mixer(self, p: Prototype) -> Mixer:
        return Mixer(id=p.id, name=self.loc.text(p.data.get("verbText"), p.id) or p.id)

    # --- entities and sources ------------------------------------------------------------

    def _entity_name(self, entity_id: str) -> str:
        proto = self.index.get("entity", entity_id)
        if proto is not None:
            name = self.loc.text(proto.data.get("name"))
            if name:
                return name
        return self.loc.get(f"ent-{entity_id}") or entity_id

    def entity(self, entity_id: str) -> Entity | None:
        proto = self.index.get("entity", entity_id)
        if proto is None:
            self.log.add("unknown-entity", f"entity {entity_id} is referenced but not defined")
            return None
        desc = self.loc.text(proto.data.get("description")) or self.loc.get(f"ent-{entity_id}.desc")
        return Entity(
            id=entity_id,
            name=self._entity_name(entity_id),
            desc=desc,
            source_file=proto.source_file,
            server_only=self._server_only("entities", entity_id),
        )

    def source(self, p: Prototype) -> Source | None:
        extractable = p.component("Extractable")
        if extractable is None:
            return None
        juice = _reagent_list((extractable.get("juiceSolution") or {}).get("reagents"))
        grind: dict[str, float] = {}
        if (name := extractable.get("grindableSolutionName")) is not None:
            grind = _solution_reagents(p, str(name))
        if not grind and not juice:
            return None
        return Source(entity=p.id, grind=grind or None, juice=juice or None)


# --- helpers -------------------------------------------------------------------------------


def _solution_reagents(entity: Prototype, solution_id: str | None) -> dict[str, float]:
    """Reagents in an entity's inline ``Solution`` component (``id`` must match when given)."""
    comp = entity.component("Solution")
    if comp is None:
        return {}
    if solution_id is not None and comp.get("id") not in (None, solution_id):
        return {}
    return _reagent_list((comp.get("solution") or {}).get("reagents"))


def _reagent_list(items: object) -> dict[str, float]:
    out: dict[str, float] = {}
    for item in items if isinstance(items, list) else []:
        if isinstance(item, dict) and "ReagentId" in item:
            rid = str(item["ReagentId"])
            out[rid] = out.get(rid, 0) + float(item.get("Quantity", 0))
    return {k: v for k, v in out.items() if v > 0}


def _entity_ids(node: object) -> Iterable[str]:
    """Every ``id:`` in an entity-table/container-fill tree (selectors nest arbitrarily)."""
    if isinstance(node, dict):
        if isinstance(node.get("id"), str):
            yield node["id"]
        for value in node.values():
            yield from _entity_ids(value)
    elif isinstance(node, list):
        for item in node:
            if isinstance(item, str):
                yield item
            else:
                yield from _entity_ids(item)


def _amount(value: object) -> float:
    return float(value)  # type: ignore[arg-type]


def _count(value: object) -> int:
    number = float(value)  # type: ignore[arg-type]
    if not number.is_integer():
        raise ValueError(f"solid count must be whole, got {number}")
    return int(number)


def _float_or_none(value: object) -> float | None:
    if value is None:
        return None
    return float(value)  # type: ignore[arg-type]


def _str_or_none(value: object) -> str | None:
    return str(value) if value is not None else None


def _jsonable(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(k): _jsonable(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_jsonable(v) for v in value]
    if isinstance(value, float) and not math.isfinite(value):
        return str(value)
    if value is None or isinstance(value, str | int | float | bool):
        return value
    return str(value)
