// Generates src/generated/*.ts from schema/ss14help.schema.json (exported by the pipeline).
// Run `uv run ss14help-pipeline schema` first. Never edit the generated files by hand.
import { readFile, writeFile } from "node:fs/promises";
import { compile } from "json-schema-to-typescript";

const schemaUrl = new URL("../../../schema/ss14help.schema.json", import.meta.url);
const outDir = new URL("../src/generated/", import.meta.url);
const banner = "// Generated by packages/schema/scripts/generate.mjs. Do not edit.\n";

const schema = JSON.parse(await readFile(schemaUrl, "utf8"));
const types = await compile(schema, schema.title, {
  bannerComment: banner,
  additionalProperties: false,
  unreachableDefinitions: true,
  format: true,
  style: { printWidth: 100, singleQuote: false, trailingComma: "all" },
});

await writeFile(new URL("types.ts", outDir), types);
await writeFile(
  new URL("version.ts", outDir),
  `${banner}export const SCHEMA_VERSION = ${JSON.stringify(schema["x-schemaVersion"])};\n`,
);
console.log(`generated types for schema ${schema["x-schemaVersion"]}`);
